# Generated by Django 4.0.2 on 2022-04-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
    ]
