# Generated by Django 4.0.2 on 2022-04-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0002_remove_payment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='transection',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
