# Generated by Django 4.0.2 on 2022-04-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0003_remove_payment_amount_transection_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transection',
            name='amount',
        ),
    ]
