# Generated by Django 4.0.2 on 2022-05-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0004_remove_transection_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
