# Generated by Django 4.0.2 on 2022-05-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orders_payment_id_alter_orders_shipping_time'),
        ('transection', '0005_transection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orders'),
        ),
    ]
