# Generated by Django 4.0.2 on 2022-05-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0006_alter_transection_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transection',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='transection',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transection',
            name='user_id',
        ),
    ]
