# Generated by Django 4.0.2 on 2022-05-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0007_remove_transection_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transection',
            old_name='payment_id',
            new_name='transaxtion_id',
        ),
    ]
