# Generated by Django 4.0.2 on 2022-06-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
