# Generated by Django 4.0.2 on 2022-05-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='shippingpolicy',
            options={'verbose_name_plural': 'Shipping Policy'},
        ),
    ]
