# Generated by Django 4.0.2 on 2022-04-14 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_category', '0003_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
