# Generated by Django 4.0.2 on 2022-04-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_category', '0005_product_price'),
        ('order', '0002_alter_orders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products_category.product'),
        ),
    ]
