# Generated by Django 4.0.2 on 2022-04-26 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 20, 45, 1, 307430), editable=False, null=True),
        ),
    ]
