# Generated by Django 4.0.2 on 2022-04-26 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orders_shipping_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 0, 31, 54, 866785), editable=False, null=True),
        ),
    ]
