# Generated by Django 4.0.2 on 2022-05-25 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orders_shipping_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 21, 7, 32, 377927), editable=False, null=True),
        ),
    ]
