# Generated by Django 4.0.2 on 2022-05-29 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orders_payment_id_alter_orders_shipping_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 1, 47, 47, 269788), editable=False, null=True),
        ),
    ]
