# Generated by Django 4.0.2 on 2022-05-29 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orders_shipping_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 2, 32, 23, 233093), editable=False, null=True),
        ),
    ]
