# Generated by Django 4.0.2 on 2022-06-07 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orders_shipping_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 4, 46, 13, 996655), editable=False, null=True),
        ),
    ]
